---
version: '3.4'

volumes:
  data-jfrog: {}

services:

  jfrog:
    image: docker.bintray.io/jfrog/artifactory-oss:latest
    container_name: jfrog-proxy
    environment:
      - TZ=Europe/Berlin
      - EXTRA_JAVA_OPTIONS=-Dartifactory.maven.suppressPomConsistencyChecks=true
    volumes:
      - data-jfrog:/var/opt/jfrog/artifactory
    ports:
      - 8081:8081

